# Imagen base para runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

# Imagen para build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release

WORKDIR /src

# Copia todo el proyecto (asumiendo que el Dockerfile ya está dentro de NuevaNaturalezaAPI.NET)
COPY . .

# Restaura dependencias
RUN dotnet restore "NuevaNaturalezaAPI.NET.csproj"

# Compila
RUN dotnet build "NuevaNaturalezaAPI.NET.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Publica
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "NuevaNaturalezaAPI.NET.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Imagen final
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://0.0.0.0:8880
ENTRYPOINT ["dotnet", "NuevaNaturalezaAPI.NET.dll"]
